version: 2
project_name: steam-web-pp-cli
changelog:
  disable: true
builds:
  - id: steam-web-pp-cli
    main: ./cmd/steam-web-pp-cli
    binary: steam-web-pp-cli
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/mvanhorn/printing-press-library/library/media-and-entertainment/steam-web-pp-cli/internal/cli.version={{ .Version }}
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - windows_amd64
      - windows_arm64
  - id: steam-web-pp-mcp
    main: ./cmd/steam-web-pp-mcp
    binary: steam-web-pp-mcp
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - windows_amd64
      - windows_arm64
archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]
checksum:
  name_template: checksums.txt
brews:
  - name: steam-web-pp-cli
    repository:
      owner: trevin-chow
      name: homebrew-tap
    homepage: "https://github.com/mvanhorn/printing-press-library"
    description: "Official Steam Web API. Get your API key at https://steamcommunity.com/dev/apikey"
    install: |
      bin.install "steam-web-pp-cli"
      bin.install "steam-web-pp-mcp"
