package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestRenderCatalogTable_Golden locks the rendering of a worst-case
// row: backticks live inside the link text (Name and Skill columns),
// the description carries punctuation we don't want to over-escape
// (commas, parentheses, an apostrophe, a hyphen). If markdown escaping
// ever changes here, the table cell display in the README changes.
// The per-row format is the documented surface; protect it.
func TestRenderCatalogTable_Golden(t *testing.T) {
	entries := []RegistryEntry{
		{
			Name:        "hubspot-pp-cli",
			Category:    "sales-and-crm",
			API:         "HubSpot",
			Description: "Work with contacts, companies, deals, tickets, and pipelines.",
			Path:        "library/sales-and-crm/hubspot",
		},
	}

	got := renderCatalogTable(entries)

	want := `<!-- this section is generated by tools/generate-registry; do not hand-edit -->
| Name | Skill | Release | What it does |
|------|-------|---------|--------------|
| [` + "`hubspot-pp-cli`" + `](library/sales-and-crm/hubspot/) | [` + "`/pp-hubspot-pp-cli`" + `](cli-skills/pp-hubspot-pp-cli/SKILL.md) | [latest](https://github.com/mvanhorn/printing-press-library/releases/tag/hubspot-pp-cli-current) | Work with contacts, companies, deals, tickets, and pipelines. |
`

	if got != want {
		t.Errorf("renderCatalogTable mismatch\nwant:\n%s\ngot:\n%s", want, got)
	}
}

// TestFormatDescription covers the normalization rules: trim, collapse
// newlines (a description must fit one table cell), and ensure
// terminal punctuation. The "?" / "!" branch matters because some
// descriptions are written as questions and we shouldn't append a
// trailing period in that case.
func TestFormatDescription(t *testing.T) {
	cases := []struct {
		name string
		in   string
		want string
	}{
		{"trims and adds period", "  hello world  ", "hello world."},
		{"keeps existing period", "hello.", "hello."},
		{"keeps existing question mark", "really?", "really?"},
		{"keeps existing exclamation", "wow!", "wow!"},
		{"collapses LF newlines", "line one\nline two", "line one line two."},
		{"collapses CRLF newlines", "line one\r\nline two", "line one line two."},
		{"empty stays empty", "   ", ""},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := formatDescription(tc.in); got != tc.want {
				t.Errorf("formatDescription(%q) = %q, want %q", tc.in, got, tc.want)
			}
		})
	}
}

// TestRenderCatalogCounts checks both pluralization branches and the
// happy multi-entry / multi-category path. The pluralization matters
// because the rendered string lands in human-readable prose; "1 CLIs
// across 1 categories" reads as a generator bug.
func TestRenderCatalogCounts(t *testing.T) {
	cases := []struct {
		name    string
		entries []RegistryEntry
		want    string
	}{
		{
			name:    "single CLI, single category",
			entries: []RegistryEntry{{Name: "a", Category: "x"}},
			want:    "1 CLI across 1 category.",
		},
		{
			name: "many CLIs, many categories",
			entries: []RegistryEntry{
				{Name: "a", Category: "x"},
				{Name: "b", Category: "y"},
				{Name: "c", Category: "x"},
			},
			want: "3 CLIs across 2 categories.",
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := renderCatalogCounts(tc.entries)
			if !strings.HasSuffix(got, tc.want) {
				t.Errorf("renderCatalogCounts: want suffix %q, got:\n%s", tc.want, got)
			}
		})
	}
}

// TestUpdateReadme_RoundTrip verifies the splice preserves surrounding
// prose and that running the generator twice on the same input is a
// byte-level no-op (idempotence — the same property registry.json
// generation already guarantees, extended to README rendering).
func TestUpdateReadme_RoundTrip(t *testing.T) {
	entries := []RegistryEntry{
		{Name: "espn", Category: "media-and-entertainment", Description: "Live scores.", Path: "library/media-and-entertainment/espn"},
	}

	src := `# Title

Intro prose.

<!-- catalog-counts:begin -->
old counts
<!-- catalog-counts:end -->

Middle prose.

<!-- catalog:begin -->
old table
<!-- catalog:end -->

Trailing prose.
`

	first, err := updateReadme([]byte(src), entries)
	if err != nil {
		t.Fatalf("first updateReadme: %v", err)
	}
	second, err := updateReadme(first, entries)
	if err != nil {
		t.Fatalf("second updateReadme: %v", err)
	}
	if string(first) != string(second) {
		t.Errorf("updateReadme not idempotent\nfirst:\n%s\nsecond:\n%s", first, second)
	}
	if !strings.Contains(string(first), "# Title") || !strings.Contains(string(first), "Intro prose.") || !strings.Contains(string(first), "Middle prose.") || !strings.Contains(string(first), "Trailing prose.") {
		t.Errorf("updateReadme dropped surrounding prose; got:\n%s", first)
	}
	if strings.Contains(string(first), "old table") || strings.Contains(string(first), "old counts") {
		t.Errorf("updateReadme failed to replace sentinel content; got:\n%s", first)
	}
}

// TestDetectMCPTransports covers the source-grep detection logic.
// Encoding the detection rule in tests guards against two regressions:
// (a) a future generator template renaming NewStreamableHTTPServer to a
//     differently-named entry point would silently flip every dual-transport
//     CLI back to stdio-only, and the test fails before the registry is
//     re-emitted.
// (b) the missing-binary fallback returning nil would cause the registry
//     to emit `"transports": null` instead of `["stdio"]`; we lock in the
//     non-nil ["stdio"] default so the JSON shape stays a real array.
func TestDetectMCPTransports(t *testing.T) {
	stdioOnlyMain := `package main

import "github.com/mark3labs/mcp-go/server"

func main() {
	s := server.NewMCPServer("Demo", "1.0.0")
	server.ServeStdio(s)
}
`
	dualTransportMain := `package main

import "github.com/mark3labs/mcp-go/server"

func main() {
	s := server.NewMCPServer("Demo", "1.0.0")
	switch *transport {
	case "stdio":
		server.ServeStdio(s)
	case "http":
		httpSrv := server.NewStreamableHTTPServer(s)
		_ = httpSrv.Start(":7777")
	}
}
`

	cases := []struct {
		name    string
		binary  string
		writeAt string // relative to cliDir; "" means don't write
		body    string
		want    []string
	}{
		{
			name:    "stdio-only binary",
			binary:  "demo-pp-mcp",
			writeAt: "cmd/demo-pp-mcp/main.go",
			body:    stdioOnlyMain,
			want:    []string{"stdio"},
		},
		{
			name:    "dual transport binary",
			binary:  "demo-pp-mcp",
			writeAt: "cmd/demo-pp-mcp/main.go",
			body:    dualTransportMain,
			want:    []string{"stdio", "http"},
		},
		{
			name:    "missing binary file falls back to stdio",
			binary:  "demo-pp-mcp",
			writeAt: "",
			want:    []string{"stdio"},
		},
		{
			name:    "empty binary name returns stdio without filesystem read",
			binary:  "",
			writeAt: "",
			want:    []string{"stdio"},
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			cliDir := t.TempDir()
			if tc.writeAt != "" {
				path := filepath.Join(cliDir, tc.writeAt)
				if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
					t.Fatalf("mkdir: %v", err)
				}
				if err := os.WriteFile(path, []byte(tc.body), 0o644); err != nil {
					t.Fatalf("write main.go: %v", err)
				}
			}
			got := detectMCPTransports(cliDir, tc.binary)
			if len(got) != len(tc.want) {
				t.Fatalf("transports = %v, want %v", got, tc.want)
			}
			for i, v := range tc.want {
				if got[i] != v {
					t.Errorf("transports[%d] = %q, want %q", i, got[i], v)
				}
			}
		})
	}
}

// TestUpdateReadme_MissingSentinels ensures updateReadme errors out
// rather than silently no-oping when a README hasn't opted into the
// sentinel scheme. Silent no-op would let drift sneak back in.
func TestUpdateReadme_MissingSentinels(t *testing.T) {
	src := `# Title

No sentinels here.
`
	_, err := updateReadme([]byte(src), nil)
	if err == nil {
		t.Fatal("expected error when sentinels missing, got nil")
	}
	if !strings.Contains(err.Error(), "missing begin sentinel") {
		t.Errorf("expected missing-sentinel error, got: %v", err)
	}
}
